apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - statsd-exporter-configmap.yaml
  - deployment.yaml
  - worker-deployment.yaml
  - feishu-bot-deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - servicemonitor.yaml
